# Generated by Django 3.1.4 on 2020-12-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_video', models.CharField(max_length=5, verbose_name='种类')),
            ],
            options={
                'verbose_name': '电影种类',
                'verbose_name_plural': '电影种类',
                'db_table': 'MovieType',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=20, verbose_name='电影名')),
                ('movie', models.CharField(max_length=100, verbose_name='url地址')),
                ('video_img_path', models.ImageField(upload_to='type')),
                ('type_foreignkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movietype', verbose_name='种类')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
                'db_table': 'Movie',
            },
        ),
    ]
